---
- name: "Run common setup plays"
  import_playbook: "../resources/playbooks/setup.yml"

- name: "Converge execution"
  hosts: "all"
  become: true

  vars:
    tautulli_docker_network_create: true

  roles:
    - "organicveggie.tautulli_docker"
