---
- name: "General setup"
  hosts: "all"
  become: true

  vars:
    pip_install_packages:
      - name: "docker"

  pre_tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        cache_valid_time: 600
        update_cache: "yes"
      when: "ansible_os_family == 'Debian'"

    - name: "Upgrade LXC"
      ansible.builtin.dnf:
        name: "lxc,lxc-templates,lxc-extra"
        state: "latest"
        update_cache: "yes"
        update_only: "yes"
      when: "ansible_os_family == 'Fedora'"

  roles:
    - "geerlingguy.pip"
    - "geerlingguy.docker"
